### ISSUE TITLE
T-NSE/F-TNSE model

### ISSUE THREAD

**Issue by YuWu14** [SENG474-TEAM-PROJECT/Reimplement-SurvivalNet#31]
Creating T-NSE model script with best variance components.
Further export F-TNSE model if necessary.
Making notes about the T-NSE/F-TNSE comparison with PCA and MDS.

**Comment by keysmon** [comment]
As suggested in our lecture, when encountering high dimensional network in neural network, TSNE is used to visualize the relationship between dimensions. Essentially, PCA is first used to suppress some noise and reduce the dimension of our data to a TSNE computable amount(roughly 100), and then we use TSNE to reduced multi-dimensions even more to a more human readable amount
