### ISSUE TITLE
Data cleaning process

### ISSUE THREAD

**Issue by samsara138** [SENG474-TEAM-PROJECT/Reimplement-SurvivalNet#36]
1)Improve API. Have ***only one*** script that utilizes all your functions and has customizable and default parameters. 
2)Bring back convert.py, for now, rename the 'Survival' column to 'Lable'. We might need to change the label in the near future

**Comment by keysmon** [comment]
script made -> clean_data.py
def clean_data(df,label = "survival",PCA_ = True,MDS_ = False, TSNE_ = False,PCA_n = 0.9,MDS_n = 2,TSNE_n = 3):

**Comment by samsara138** [comment]
3) better readme.md
