### ISSUE TITLE
Importing problem

### ISSUE THREAD

**Issue by samsara138** [SENG474-TEAM-PROJECT/Reimplement-SurvivalNet#38]
Cannot import BuildData from the root directory
`ImportError: No module named firebrowse.highlevel`
The script works fine when calling it directly by using
`python TCGAIntegrator/BuildData.py`
suspect something to do with the __init__.py
Can't figure it out. Running it directly and getting the result instead. Suggest ask prof

**Comment by RoyLQ** [comment]
SOLUTION: creating an empty  _init_.py file
DONE
